pipeline {
  agent any

  tools {
    nodejs 'NodeJS-18'
  }

  environment {
    SCANNER_HOME = tool 'sonar-scanner'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('Application-Code') {
          sh 'yarn install'
        }
      }
    }

    stage('Build React App') {
      steps {
        dir('Application-Code') {
          sh 'yarn build'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('Application-Code') {
          withSonarQubeEnv('sonar-server') {
            sh '''
              $SCANNER_HOME/bin/sonar-scanner \
              -Dsonar.projectName=Netflix \
              -Dsonar.projectKey=Netflix \
              -Dsonar.sources=src
            '''
          }
        }
      }
    }
    stage("quality gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token'
                }
            }
        }
    
    stage('Install Dependencies') {
        steps {
                sh "npm install"
            }
        }
    }
  }
}
    post {
     always {
        emailext attachLog: true,
            subject: "'${currentBuild.result}'",
            body: "Project: ${env.JOB_NAME}<br/>" +
                "Build Number: ${env.BUILD_NUMBER}<br/>" +
                "URL: ${env.BUILD_URL}<br/>",
            to: 'mahmoudyousef6868@gmail.com',
            attachmentsPattern: 'trivyfs.txt,trivyimage.txt'
        }
    }
}
