pipeline {
  agent any

  tools {
    nodejs 'NodeJS-18'
  }

  environment {
    SCANNER_HOME = tool 'sonar-scanner'
    TMDB_API_KEY = credentials('TMDB_API_KEY')
    DOCKER_IMAGE = 'mahmoudtots/netflix'
  }

  stages {

    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('Application-Code') {
          sh 'yarn install'
        }
      }
    }

    stage('Build') {
      steps {
        dir('Application-Code') {
          sh 'yarn build'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('Application-Code') {
          withSonarQubeEnv('sonar-server') {
            sh '''
              $SCANNER_HOME/bin/sonar-scanner \
              -Dsonar.projectName=Netflix \
              -Dsonar.projectKey=Netflix \
              -Dsonar.sources=src
            '''
          }
        }
      }
    }

    stage('Quality Gate') {
      steps {
        waitForQualityGate abortPipeline: true
      }
    }
    stage('OWASP FS SCAN') {
            steps {
              dir('Application-Code') {
                withCredentials([string(credentialsId: 'NVD_API_KEY', variable: 'NVD_API_KEY')]) {
                dependencyCheck additionalArguments: '--disableYarnAudit --disableNodeAudit', odcInstallation: 'dependency-check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
              }
            }
        }
        stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs Application-Code > trivyfs.txt"
            }
        }
        stage('Docker Build & Push') {
          steps {
            dir('Application-Code') {
              withCredentials([usernamePassword(credentialsId: 'docker-cred',usernameVariable: 'DOCKER_USER',passwordVariable: 'DOCKER_TOKEN')]) {
                sh '''
                echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

                docker build \
                --build-arg VITE_APP_API_ENDPOINT_URL=https://api.themoviedb.org/3 \
                --build-arg VITE_APP_TMDB_V3_API_KEY=$TMDB_API_KEY \
                -t $DOCKER_IMAGE:latest .
                
                docker push $DOCKER_IMAGE:latest
                '''
              }
            }
         }
        } 
        stage("TRIVY IMAGE SCAN"){
            steps{
                sh "trivy image $DOCKER_IMAGE:latest > trivyimage.txt" 
            }
        }
        stage('Deploy to container'){
            steps{
                sh '''
                  docker rm -f netflix || true
                  docker run -d --name netflix -p 8081:80 $DOCKER_IMAGE:latest
                    '''

            }
        } 
  }
}
