pipeline {
  agent any

  tools {
    nodejs 'NodeJS-18'
  }

  environment {
    SCANNER_HOME=tool 'sonar-scanner'
    SONAR_HOST_URL = 'http://192.168.251.30:9000'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('Application-Code') {
          sh 'yarn install'
        }
      }
    }

    stage('Build React App') {
      steps {
        dir('Application-Code') {
          sh 'yarn build'
        }
      }
    }

        stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Netflix \
                    -Dsonar.projectKey=Netflix '''
                }
            }
        }


    stage('OWASP Dependency Check') {
      steps {
        dir('Application-Code') {
          sh 'dependency-check --project netflix-react --scan .'
        }
      }
    }
  }
}

